shortcuts:
  dev:
    pipeline_name: qa
    args:
      path: .
      clean: False
      sync: True
      style: True
      lint: True
      test: True
      integration: False
      build: True
      stats: False

  ci:
    pipeline_name: qa
    args:
      path: .
      clean: True
      sync: True
      style: False
      lint: True
      test: True
      integration: False
      build: True
      stats: True
