name: SemanticKernelSampler.DotNet

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - dotnet/SemanticKernelSampler.DotNet/**
      - .github/workflows/dotnet_ci.yml
      - .github/workflows/branch.dotnet.SemanticKernelSampler.yml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dotnet_ci:
    name: dotnet build
    uses: ./.github/workflows/dotnet_ci.yml
    with:
      dotnet-project-name: SemanticKernelSampler.DotNet
      dotnet-project: ./*.sln
      dotnet-version: 8
      dotnet-target-framework: net8.0
