name: "agent-framework-sampler-py"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    # paths:
    #   - "python/agent-framework-sampler-py/**"
  push:
    branches-ignore:
      - "main"
    # paths:
    #   - "python/agent-framework-sampler-py/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/ci_uv.yml
    with:
        working-directory: python/agent-framework-sampler-py
