name: "[C]ontinuous [I]ntegration: rest-app"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches-ignore:
      - "main"
    # paths:
    #   - "node/rest-app/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  NODE_PROJECT: rest-app
  WORKSPACE: node/rest-app
  NPM_CLI_OPTS: --prefix node/rest-app

jobs:
  npm_test:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
