name: AgentFrameworkSampler.DotNet

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - dotnet/AgentFrameworkSampler.DotNet/**
      - .github/workflows/dotnet_ci.yml
      - .github/workflows/branch.dotnet.AgentFrameworkSampler.yml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  uv_ci:
    uses: ./.github/workflows/dotnet_ci.yml
    with:
      dotnet-project-name: AgentFrameworkSampler.DotNet
      dotnet-project: ./*.slnx
      dotnet-version: 9
      dotnet-target-framework: net9.0
