name: SemanticKernelSampler.DotNet

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - dotnet/SemanticKernelSampler.DotNet/**
      - .github/workflows/branch.dotnet.SemanticKernelSampler.yml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  uv_ci:
    uses: ./.github/workflows/dotnet_ci.yml
    with:
      dotnet-project-name: dotnet/SemanticKernelSampler.DotNet
      dotnet-project: ./*.sln
      dotnet-version: 8
      dotnet-target-framework: net8.0
