name: "[C]ontinuous [I]ntegration: rest-app"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches-ignore:
      - "main"
    # paths:
    #   - "node/rest-app/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22
  NODE_PROJECT: rest-app
  WORKSPACE: node/$(NODE_PROJECT)

jobs:
  npm_test:
    name: npm test @ $(NODE_PROJECT)
    runs-on: ubuntu-latest
    env:
      NPM_CLI_OPTS: --prefix $(WORKSPACE)
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -la ${{ env.WORKSPACE }}

      - name: node @ ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm run setup:ci
        run: npm run setup:ci --if-present ${{ env.NPM_CLI_OPTS }}
      - name: npm install
        run: npm ci ${{ env.NPM_CLI_OPTS }}
      - name: ls node_modules
        run: ls -la ${{ env.WORKSPACE }}/node_modules

      - name: npm test
        run: npm test ${{ env.NPM_CLI_OPTS }}
