name: "[C]ontinuous [I]ntegration: mcp-server.rest-app.posts"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches-ignore:
      - "main"
    paths:
      - "node/rest-app/**"
      - "node/mcp-server.rest-app.posts/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

  WORKSPACE: ./node/mcp-server.rest-app.posts

jobs:
  npm_test:
    runs-on: ubuntu-latest
    env:
      NPM_CLI_OPTS: --prefix ${{ env.WORKSPACE }}
    name: npm test @  ${{ env.WORKSPACE }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -la ./node/ ${{ env.WORKSPACE }}

      - name: node @ ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm run setup:ci
        run: npm run setup:ci --if-present ${{ env.NPM_CLI_OPTS }}
      - name: npm install
        run: npm ci ${{ env.NPM_CLI_OPTS }}
      - name: ls node_modules
        run: ls -la ${{ env.WORKSPACE }}/node_modules

      - name: npm test
        run: npm test ${{ env.NPM_CLI_OPTS }}
