name: "mcp-server.examples.quick-start"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - "node/mcp-server.examples.quick-start/**"
      - ".github/workflows/branch.node.mcp-server.examples.quick-start.yml"
  push:
    branches-ignore:
      - "main"
    paths:
      - "node/mcp-server.examples.quick-start/**"
      - ".github/workflows/branch.node.mcp-server.examples.quick-start.yml"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  verify:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      # script: test  # default
      working-directory: node/mcp-server.examples.quick-start
