name: node

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - package*.json
      - node/**
      - .github/workflows/branch.node.yml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  verify:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    # with:
    #   script: test  # default

  codeQL:
    needs: verify
    permissions:
      actions: read
      contents: read
      security-events: write

    name: CodeQL
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    with:
      language: javascript
