name: "[C]ontinuous [I]ntegration @ main"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  # XXX? not being used
  REPOSITORY_NAME: ${{ github.event.repository.name }}

  # node & npm
  NODE_VERSION: 22

  # .NET
  DOTNET_CONFIGURATION: Release

  # Dockerfile(s) & docker compose
  DOCKER_BUILDKIT: 1
  DOCKER_TAG_VERSION: latest

jobs:
  lint:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      script: lint

  codeQL:
    needs: lint
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - actions
          - python
          - javascript
          # - csharp  # TODO
          # - java  # TODO

    name: "CodeQL: ${{ matrix.language }}"
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    with:
      language: ${{ matrix.language }}

  npm_test__matrix:
    needs: lint
    strategy:
      max-parallel: 6
      matrix:
        project:
          - mcp-server.examples.quick-start
          - rest-app
          - mcp-server.rest-app.posts

    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      # script: test  # default
      working-directory: ./node/${{ matrix.project }}

  npm_test:
    name: npm test
    needs: npm_test__matrix
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    # with:
    #   script: test  # default

  python_ci__matrix:
    needs: lint
    strategy:
      max-parallel: 6
      matrix:
        project:
          - semantic-kernel-sampler-py
          - agent-framework-sampler-py
          - ai-evaluator-py

    uses: ./.github/workflows/uv_ci.yml
    with:
      working-directory: python/${{ matrix.project }}

  dotnet_build__matrix:
    needs: lint
    strategy:
      max-parallel: 6
      matrix:
        include:
          - project: SemanticKernelSampler.DotNet
            DOTNET_PROJECT: ./*.sln
            DOTNET_VERSION: 8
            DOTNET_TARGET_FRAMEWORK: net8.0

          - project: AgentFrameworkSampler.DotNet
            DOTNET_PROJECT: ./*.slnx
            DOTNET_VERSION: 9
            DOTNET_TARGET_FRAMEWORK: net9.0

    uses: ./.github/workflows/dotnet_ci.yml
    with:
      dotnet-project-name: ${{ matrix.project }}
      dotnet-project: ${{ matrix.DOTNET_PROJECT }}
      dotnet-version: ${{ matrix.DOTNET_VERSION }}
      dotnet-target-framework: ${{ matrix.DOTNET_TARGET_FRAMEWORK }}

  mvn_verify:
    needs: lint
    uses: ./.github/workflows/mvn_verify.yml

  docker_compose_build:
    name: docker compose build
    runs-on: ubuntu-latest
    needs:
      - npm_test
      - dotnet_build__matrix
      - python_ci__matrix
      - mvn_verify
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: bower install
        run: npm run bower:install:production

      - name: config
        run: |
          cd node/mcp-server.rest-app.posts/src/config/
          cp docker.windows.ts active.ts
          cd ../../../..

      - name: docker compose build
        run: docker compose build

  docker_build__matrix:
    needs: docker_compose_build
    continue-on-error: true
    permissions:
      contents: read
      security-events: write

    strategy:
      max-parallel: 10
      matrix:
        include:
          #
          # root
          # NOTE: Tested in docker compose
          # - working-directory: .
          #   target: modelcontextprotocol.inspector
          #   scan-image: false

          - project-name: node
            working-directory: .
            target: tested
            scan-image: false

          #
          # semantic-kernel-sampler-py
          - project-name: semantic-kernel-sampler-py
            working-directory: python/semantic-kernel-sampler-py
            target: tested
            scan-image: false

          - project-name: semantic-kernel-sampler-py
            working-directory: python/semantic-kernel-sampler-py
            target: release
            scan-image: ${{ github.ref == 'refs/heads/main' }}

          #
          # agent-framework-sampler-py
          - project-name: agent-framework-sampler-py
            working-directory: python/agent-framework-sampler-py
            target: tested
            scan-image: false

          - project-name: agent-framework-sampler-py
            working-directory: python/agent-framework-sampler-py
            target: release
            scan-image: ${{ github.ref == 'refs/heads/main' }}

    name: docker build ${{ matrix.working-directory }}.${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-docker/.github/actions/build@main
        with:
          repository_name: ${{ github.event.repository.name }}.${{ matrix.project-name }}
          working-directory: ${{ matrix.working-directory }}
          target: ${{ matrix.target }}
          scan-image: ${{ matrix.scan-image }}
