name: "[C]ontinuous [I]ntegration @ main"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

  ARCHITECTURE: x64

  # node & npm
  NODE_VERSION: 22

  # .NET
  DOTNET_CONFIGURATION: Release

  # Java
  JDK_VERSION: 11
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
  MAVEN_CLI_OPTS: --batch-mode --update-snapshots

  # Dockerfile(s) & docker compose
  DOCKER_BUILDKIT: 1
  DOCKER_TAG_VERSION: latest

jobs:
  lint:
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      script: lint

  npm_test__matrix:
    needs: lint
    strategy:
      max-parallel: 6
      matrix:
        project:
          - mcp-server.examples.quick-start
          - rest-app
          - mcp-server.rest-app.posts

    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      # script: test  # default
      working-directory: ./node/${{ matrix.project }}

  npm_test:
    name: npm test
    needs: npm_test__matrix
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    # with:
    #   script: test  # default

  python_ci__matrix:
    needs: lint
    strategy:
      max-parallel: 6
      matrix:
        project:
          - semantic-kernel-sampler-py
          - agent-framework-sampler-py
          - ai-evaluator-py

    uses: ./.github/workflows/uv_ci.yml
    with:
      working-directory: python/${{ matrix.project }}

  dotnet_build__matrix:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        include:
          - project: SemanticKernelSampler.DotNet
            DOTNET_PROJECT: ./*.sln
            DOTNET_VERSION: 8
            DOTNET_TARGET_FRAMEWORK: net8.0

          - project: AgentFrameworkSampler.DotNet
            DOTNET_PROJECT: ./*.slnx
            DOTNET_VERSION: 9
            DOTNET_TARGET_FRAMEWORK: net9.0
    env:
      WORKSPACE: ./dotnet/${{ matrix.project }}
    name: dotnet build @ ${{ matrix.project }}
    steps:
      - name: .NET @ ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: checkout
        uses: actions/checkout@v4

      - name: ls
        run: ls -la
        working-directory: ${{ env.WORKSPACE }}

      - name: dotnet restore
        run: dotnet restore ${{ env.DOTNET_PROJECT }}
        working-directory: ${{ env.WORKSPACE }}

      - name: dotnet build
        run: |
          dotnet build ${{ env.DOTNET_PROJECT }} \
            --no-restore \
            --configuration ${{ env.DOTNET_CONFIGURATION }} \
            /p:TreatWarningsAsErrors=true
        working-directory: ${{ env.WORKSPACE }}

      - name: bin.zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}.WebApp.zip
          path: ${{ env.WORKSPACE }}/WebApp/bin/${{ env.DOTNET_CONFIGURATION }}/${{ env.DOTNET_TARGET_FRAMEWORK }}

  mvn_verify:
    needs: lint
    name: mvn verify
    runs-on: ubuntu-latest
    steps:
      - name: JDK @ ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          architecture: ${{ env.ARCHITECTURE }}
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: checkout
        uses: actions/checkout@v4

      - name: ls
        run: ls -la
        working-directory: ./java

      - name: mvn verify
        run: mvn ${{ env.MAVEN_CLI_OPTS }} verify
        working-directory: ./java

      - name: target.zip
        uses: actions/upload-artifact@v4
        with:
          name: SemanticKernelSampler.Java.WebApp.zip
          path: ./java/target

  docker_compose_build:
    name: docker compose build
    runs-on: ubuntu-latest
    needs:
      - npm_test
      - dotnet_build__matrix
      - python_ci__matrix
      - mvn_verify
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: node @ ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm run setup:ci
        run: npm run setup:ci --if-present ${{ env.NPM_CLI_OPTS }}
      - name: bower install
        run: npm run bower:install:production

      - name: config
        run: |
          cd node/mcp-server.rest-app.posts/src/config/
          cp docker.windows.ts active.ts
          cd ../../../..

      - name: docker compose build
        run: docker compose build
